Add files via upload
Kim-Yeon-ho/2023_SoftwareEng01 pull request #13
Opened 2023-11-09 09:45 UTC by dkfneodn

## 🌁 배경
- 작업이 이루어진 이유

## 👩‍💻 작업 내용 (Content)
- 리뷰어가 중점적으로 봐야 하는 부분을 바로 알 수 있도록 변경된 내용을 작성합니다.

## 📱 스크린샷
- 화면 전환이나 인터렉션이 있는 경우엔 GIF, 정적인 화면이라면 스크린샷을 이용합니다.

<p align="left">
  <img width="200" alt="스크린샷1" src="사진URL">
  <img width="200" alt="스크린샷2" src="사진URL">
  <img width="200" alt="스크린샷3" src="사진URL">
</p>

## ✅ 테스트방법
- PR리뷰어가 변경사항을 확인할 수 있는 방법을 서술합니다.

## 📣 PR & Issues
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.

## 📬 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

- Closed #이슈넘버 ( PR이 merge 될 때 이슈가 같이 close 됩니다. )

2023-11-09 14:21 UTC, iiinsk requested changes
input == '='부분을 while문에 포함시켜야 할 것 같습니당.

2023-11-09 14:21 UTC, iiinsk commented on isInteger.py
> +                print("= ERROR!")
input이 '='인지 검사하는 if문은 while문 안에 있어야 할 것 같아요.

2023-11-10 01:13 UTC, Kim-Yeon-ho requested changes
기존에 메인코드가 바뀌어서 바뀐 코드로 진행부탁드립니다!

2023-11-10 02:19 UTC, dkfneodn commented on isInteger.py
> +                print("= ERROR!")
바뀐 메인코드로 다시 수정하겠습니다 !

2023-11-10 04:47 UTC, Kim-Yeon-ho commented on isInteger.py
> +...         return isEmpty
return isEmpty가 두개인데 하나는 if문 안에 들어가고 하나는 클래스 전체의 return값인가요?
그리고 isEmpty는 isEmpty()로 해서 보통 함수로 있어서 변수를 쓴다면 같은 네이밍은 피하는 게 좋을 것 같습니다.

2023-11-10 05:50 UTC, dkfneodn commented on isInteger.py
> +...         return isEmpty
불여넣기 할 때 잘못한 거 같습니다 ! return isEmpty는 하나가 맞습니다 ! 수정해서 다시 올리겠습니다 !

2023-11-11 04:42 UTC, jeon-seong-hyuk commented
코드 적는 파일이 isInteger.py이 아니라 main.py에 적으셔야 해요.

2023-11-13 00:45 UTC, Kim-Yeon-ho commented
저희 팀 레포에 있는 파일을 pull받아서 작업진행해주셔야합니다!

2023-11-13 07:54 UTC, dlwngud629 commented
isInteger() 함수 부분 잘 동작하는것 같아요!

2023-11-13 07:57 UTC, Kim-Yeon-ho commented
항상 PULL 받기 전에 팀레포에 변경사항이 생기면 항상 PULL받고 컨플릭 해결 해주세요

2023-11-13 08:02 UTC, Kim-Yeon-ho approved these changes

2023-11-13 08:24 UTC, jeon-seong-hyuk approved these changes
정상적으로 잘 되네요. 고생하셨습니다.

2023-11-13 11:48 UTC, dlwngud629 approved these changes

2023-11-13 14:16 UTC, iiinsk approved these changes
수고하셨습니다.

2023-11-13 14:32 UTC, Kim-Yeon-ho requested changes
컨플릭 해결해주세요

2023-11-13 15:27 UTC, Kim-Yeon-ho commented
고생하셨습니다!! 1번부터 6번까지 주석줄만 지워주시고 머지하면 될 것 같습니다:)

2023-11-13 15:27 UTC, Kim-Yeon-ho approved these changes

2023-11-13 16:16 UTC, merged