main 함수 코드 작성
Kim-Yeon-ho/2023_SoftwareEng01 pull request #9
Opened 2023-11-06 10:55 UTC by dlwngud629

## 🌁 배경
-SRS을 기반으로 main함수를 작성했습니다.

## 👩‍💻 작업 내용 (Content)
- main함수와 추가해야될 함수의 이름만 선언해뒀습니다. 각 함수에 들어갈 내용은 역할에 맞게 채우시면 됩니다! 자유롭게 수정하셔도 됩니다.

## ✅ 테스트방법
- 아직 함수들이 작성되지 않아 테스트는 불가능 합니다.

## 📬 참고문서, 레퍼런스
- https://madplay.github.io/post/python-main-function  #파이썬의 main함수 실행에 관한 내용입니다.

2023-11-06 11:37 UTC, Kim-Yeon-ho commented
- Closed #189 처럼 PR작성하실때 이슈번호 적으시면 PR이 머지될 떄 이슈가 저절로 close됩니다.

2023-11-06 12:10 UTC, Kim-Yeon-ho requested changes

2023-11-06 12:10 UTC, Kim-Yeon-ho commented on main.py
> +        if isDivision(entry) and isInteger(entry): #enty가 나눗셈이 아니고 정수라면
예외 처리를 따로 스택을 만들지 않고, 입력은 정수로 한정되어있으니 입력값을
int(input()) 으로 고정 시킨 뒤에 try except 구문 활용해서 따로 빼면 어떨까요?

2023-11-06 14:01 UTC, iiinsk reviewed
제가 예외처리 담당이니 ErrorStack부분은 구현하면서 수정해보겠습니다.
계산기 함수와 메인스택 구현하실 때 가급적 Error에 관련된 내용을 스택에 넣지 않는 방향으로만 구현해주시면 감사하겠습니다.

2023-11-06 14:01 UTC, iiinsk commented on main.py
> +        return
입력에 실수형이나 나눗셈이 포함되면 무조건 Error가 출력되므로 ErrStack을 구현하는 방향보단 main내부에서 반복문을 통해 입력값을 검사하며 분기하는것은 어떤가요?

Input: 1 + 2 + 3 + ... 99 / 100    Output: Error

위와같이 아무리 크더라도 한번만 예외사항이 포함되면 무조건 Err를 출력하니 

boolen err_checker = false;
while(1)
{
   if(input == / || input == 실수형) 
   { 
      err_checker = true;
      input -> stack
      (이 부분에서 Error이후의 입력값은 스택에 넣지 않아도 괜찮을 것 같아요.)
   }
   else 
      if(input == "=") { 계산함수 호출 };
      input -> stack;    
}

이런 방식으로 처리하면 errstack을 구현하지 않아도 되지 않을까 싶어요.

2023-11-07 08:20 UTC, dlwngud629 commented on main.py
> +        return
error stack에 넣지 않도록 main코드를 수정하였습니다!

2023-11-07 08:20 UTC, dlwngud629 commented on main.py
> +        if isDivision(entry) and isInteger(entry): #enty가 나눗셈이 아니고 정수라면
try execpt 문을 사용하니 코드가 훤씬 간결해지네요. 수정했습니다~

2023-11-07 16:58 UTC, Kim-Yeon-ho approved these changes
고생하셨습니다!

2023-11-09 00:10 UTC, dkfneodn approved these changes

2023-11-09 01:41 UTC, jeon-seong-hyuk requested changes

2023-11-09 01:41 UTC, jeon-seong-hyuk commented on main.py
> +            entry = int(input("숫자 혹은 연산자를 입력하세요: ")) #entry변수로 사용자 입력을 저장
int(input())을 main함수 안에 inputInt = int(input("숫자를 입력하세요: "))와 inputStr = input("연산자를 입력하세요: ")를 작성하시고 try부분에서 entry = inputInt와 inputStr로 하시는 게 깔끔해 보일 거 같아요.

그리고 input()은 str만 입력되고 int(input())은 int만 입력되서
번갈아 가면서 입력해야 할 것 같아요

2023-11-09 05:11 UTC, Kim-Yeon-ho commented on main.py
> +            entry = int(input("숫자 혹은 연산자를 입력하세요: ")) #entry변수로 사용자 입력을 저장
아 int(input()) 하면은 연산자 자체도 오류로 입력되니 그게 맞네요!

2023-11-09 12:27 UTC, Kim-Yeon-ho commented on main.py
> +        if(not isInteger()):
isInteger() 함수가 잘 돌아가는 함수가 맞나요?? 제가 찾아보니까 우선 is_Integer()로 작성이 되고
로직이 isInteger()가 어떤 값이 정수인지 아닌지 비교하는지 없는 것 같습니다.
inputInt.is_integer() 으로 작성하면 자체에서 bool값을 반환해주는 식이 맞지않을까 싶습니다!

2023-11-09 12:30 UTC, dlwngud629 commented on main.py
> +            entry = int(input("숫자 혹은 연산자를 입력하세요: ")) #entry변수로 사용자 입력을 저장
그걸 못봤네요.. try execpt문은 나누기 처리가 힘든거 같아서 if문으로 작성했습니다.

2023-11-09 13:08 UTC, dlwngud629 commented on main.py
> +        if(not isInteger()):
하하 하루종일 틀리네요.. 함수에 인자를 넘겨주는거로 바꿨습니다.

2023-11-11 04:21 UTC, jeon-seong-hyuk commented on main.py
> +        inputInt = input() #정수 입력
inputInt = int(input())으로 바꿔주세요

2023-11-11 04:21 UTC, jeon-seong-hyuk commented on main.py
> +                        #이스터에그 출력 코드 작성해주세요
이스터에그 함수 자체를 넣어주세요.
Example : easterEgg()

2023-11-11 04:21 UTC, jeon-seong-hyuk commented on main.py
> +            isEqual(inputInt)
isEqual에서 '='표시는 문자이기 때문에 inputStr를 매개변수로 해야합니다.

그리고 여기에서는 isEqual이 필요 없어 보입니다.

2023-11-11 04:21 UTC, jeon-seong-hyuk commented on main.py
> +        inputStr = input() #연산기호 입력
코드의 일관성을 위해 68줄 밑에 넣어주시면 좋겠어요.(변수끼리 있어야 보기 좋아요)

2023-11-11 04:21 UTC, jeon-seong-hyuk commented on main.py
> +            isEqual(inputStr)
여기도 isEqual()이 필요없어 보입니다.

2023-11-11 04:21 UTC, jeon-seong-hyuk commented on main.py
> +            isEqual(inputStr)
여기도isEqual()이 필요없어 보입니다.

차라리 마지막에 
if inputStr == '=':
    isEqual(inputStr)
    break
하는게 낫지 않을까요?

2023-11-11 10:01 UTC, dlwngud629 commented on main.py
> +        inputInt = input() #정수 입력
정수형 입력으로 바꾸면 inputInt에 항상 정수값이 들어가야되니 실수를 입력했을때 케이스가 사라지지 않나요?

2023-11-11 10:05 UTC, dlwngud629 commented on main.py
> +            isEqual(inputInt)
ppt에서 사용자가 =을 입력하면 출력을 해야한다고 기술된 내용을 반영한 부분입니다. 일반적인 입력은 마지막에 정수가 입력된 뒤 등호가 입력되며 결과가 출력되지만 "3 + =ERROR!" 경우를 예외처리했습니다.

2023-11-11 10:09 UTC, dlwngud629 commented on main.py
> +        inputStr = input() #연산기호 입력
마찬가지로 68번쨰 줄로 해당카드를 옮기면  "3 + = +"의 경우를 예외처리하지 못합니다.

2023-11-11 10:14 UTC, dlwngud629 commented on main.py
> +            isEqual(inputStr)
필요없는부분 맞습니다! 코드 수정했습니다~

2023-11-11 10:27 UTC, dlwngud629 commented on main.py
> +            isEqual(inputStr)
주석 추가로 적어뒀습니다!. 이렇게 구현한 이유는 스택에 등호를 넣지 않기 위함입니다.

2023-11-11 10:27 UTC, dlwngud629 commented on main.py
> +                        #이스터에그 출력 코드 작성해주세요
수정했습니다!

2023-11-11 11:18 UTC, jeon-seong-hyuk commented on main.py
> +        inputInt = input() #정수 입력
그냥 input()만 하면 문자형식으로 들어가게 되어버려서 정수 자체도 안되게 되요. 그러면 double(input())하는 게 어떨까요?

2023-11-11 11:25 UTC, jeon-seong-hyuk commented on main.py
> +        inputStr = input() #연산기호 입력
아 죄송합니다. 잘못 말씀 드렸네요. 71줄 밑을 말한 거였습니다!
그리고 inputStr와 inputInt는 변수명이 달라서 상관이 없습니다.

2023-11-11 11:41 UTC, jeon-seong-hyuk commented on main.py
> +            isEqual(inputStr)
그럼 inputStr = input()을 71줄 밑에 넣으시고, 그 다음 줄에
if(inputStr == '='):
   isEqual(inputStr)
   break
를 넣으시면 될거 같아요

2023-11-11 13:22 UTC, dlwngud629 commented on main.py
> +            isEqual(inputStr)
말씀하신대로 코드를 고치면 "3 + = ="의 경우 =이 입력됐을때 바로 에러출력이 안되는거 같아요.

2023-11-12 11:44 UTC, jeon-seong-hyuk commented on main.py
> +            isEqual(inputStr)
애초에 int형식으로 input되는 거에 =표시를 넣게 되면 파이썬 자체적으로 컴파일이 안되실거에요

2023-11-13 00:35 UTC, dlwngud629 commented on main.py
> +            isEqual(inputStr)
try:
            inputInt = int(input()) #정수 입력
            inputStr = input() #연산기호 입력

            myStack.push(inputInt)

            if(not isDivision(inputStr)):
                isEqual(inputStr) #연산자 +, *, -, = 중 =이 입력됐다면 결과 출력 
                myStack.push(inputStr) 
            else:
                isError = True

        except:
            isError = True
이걸 원하시는건가요?

2023-11-13 05:21 UTC, jeon-seong-hyuk commented on main.py
> +            isEqual(inputStr)
네 맞습니다.

2023-11-13 06:54 UTC, jeon-seong-hyuk approved these changes

2023-11-13 06:54 UTC, iiinsk approved these changes
맞게 구현된 것 같습니다.
수고하셨습니다.

2023-11-13 06:54 UTC, merged